#title: ANS ALI
#theme: jekyll-theme-minimal
#logo: 'IMG-20241209-WA0108.jpg'

title: "ANS ALI"
description: "Data Scientist | Machine Learning Engineer | AI Enthusiast"
theme: jekyll-theme-minimal
logo: "IMG-20241209-WA0108.jpg"

# Social Media Links
github: "https://github.com/yourusername"
linkedin: "https://linkedin.com/in/yourusername"
twitter: "https://twitter.com/yourusername"
email: "your.email@example.com"

# Site Settings
show_downloads: true  # Show a download link for repositories
google_analytics: "UA-XXXXXXXXX-X"  # Add your Google Analytics ID for tracking
favicon: "favicon.ico"  # Add a custom favicon
permalink: pretty  # Clean URLs without .html

# Navigation Links
navigation:
  - title: "Home"
    url: "/"
  - title: "Projects"
    url: "/projects"
  - title: "Blog"
    url: "/blog"
  - title: "Contact"
    url: "/contact"

# SEO Optimization
author: "ANS ALI"
keywords: "Data Science, Machine Learning, AI, Deep Learning, Python, Portfolio"
timezone: "UTC"

